# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Segment <- function(img, C, img_vec, GibbsN, alpha, beta, mu_0, Lambda_0, v_0, Sigma_0) {
    .Call(`_ImageSegment_Segment`, img, C, img_vec, GibbsN, alpha, beta, mu_0, Lambda_0, v_0, Sigma_0)
}

